spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${URL}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    redis:
      host: ${HOST}
      port: ${PORT}

jwt:
  secret: ${SECRET}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}